//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.6.28
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: A ()
//
module A // "a_mod"
(
);

// Variables generated for SystemC signals
logic signed [31:0] t;

//------------------------------------------------------------------------------
// Method process: methodProc (test_sizeof.cpp:26:5) 

always_comb 
begin : methodProc     // test_sizeof.cpp:26:5
    integer unsigned i;
    i = 3'd4;
    $display("U %d\n", i);
    i = 4'd8;
    $display("LU %d\n", i);
    i = 4'd8;
    $display("LLU %d\n", i);
    i = 4'd8;
    $display("ptr %d\n", i);
    i = 3'd4;
    $display("ptr %d\n", i);
    i = 4'd8;
    $display("Rec %d\n", i);
    i = 5'd24;
    $display("sc_uint<16> %d\n", i);
    i = 7'd64;
    $display("sc_biguint<64> %d\n", i);
    t = i;
end

endmodule


