//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.4.32
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: A ()
//
module A // "a_mod"
(
);

// Variables generated for SystemC signals

//------------------------------------------------------------------------------
// Method process: meth (test_multiple_pointers_mod.cpp:43:5) 
// Empty process, no code generated 


//------------------------------------------------------------------------------
// Child module instances

B b
(

);

B dpb
(

);

endmodule



//==============================================================================
//
// Module: B (test_multiple_pointers_mod.cpp:21:5)
//
module B // "a_mod.b"
(
);

endmodule


