//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.7.6
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: apb_port ()
//
module apb_port // "tbt.dut"
(
    input logic PCLK,
    input logic PRESETn,
    input logic [7:0] PADDR,
    input logic PSEL,
    input logic PENABLE,
    input logic PWRITE,
    input logic [31:0] PWDATA,
    input logic [3:0] PSTRB,
    output logic PREADY,
    output logic [31:0] PRDATA,
    output logic PSLVERR,
    input logic req_init_core_ready,
    output logic req_init_core_req,
    output logic [7:0] req_init_core_data_addr,
    output logic req_init_core_data_write,
    output logic [31:0] req_init_core_data_wdata,
    output logic [3:0] req_init_core_data_wstrb,
    output logic resp_target_core_ready,
    input logic resp_target_core_req,
    input logic [31:0] resp_target_core_data_rdata,
    input logic resp_target_core_data_slverr
);

// Variables generated for SystemC signals
logic req_init_put_req;
logic req_init_put_req_d;
logic req_init_core_req_d;
logic resp_target_get_req;
logic resp_target_get_req_d;
logic resp_target_core_req_d;
logic [31:0] resp_target_core_data_d_rdata;
logic resp_target_core_data_d_slverr;
logic [31:0] resp_target_core_data_out_rdata;
logic resp_target_core_data_out_slverr;
logic req_init_clk;
logic req_init_nrst;
logic resp_target_clk;
logic resp_target_nrst;

// Local parameters generated for C++ constants
localparam logic req_init_chan_sync = 0;
localparam logic req_init_cthread = 1;
localparam logic req_init_always_ready = 0;
localparam logic resp_target_cthread = 1;
localparam logic resp_target_always_ready = 0;
localparam logic [31:0] STATE_IDLE = '0;
localparam logic [31:0] STATE_REQUEST = 1;
localparam logic [31:0] STATE_RESPONSE = 2;
localparam logic [31:0] STATE_COMPLETE = 3;

// Assignments generated for C++ channel arrays
assign req_init_clk = PCLK;
assign req_init_nrst = PRESETn;
assign resp_target_clk = PCLK;
assign resp_target_nrst = PRESETn;

//------------------------------------------------------------------------------
// Clocked THREAD: req_init_sync_thread (sct_initiator.h:223:5) 
// Empty process, no code generated 

//------------------------------------------------------------------------------
// Clocked THREAD: req_init_core_thread (sct_initiator.h:266:5) 

// Thread-local variables
logic req_init_put_req_d_next;
logic req_init_core_req_d_next;

// Next-state combinational logic
always_comb begin : req_init_core_thread_comb     // sct_initiator.h:266:5
    req_init_core_thread_func;
end
function void req_init_core_thread_func;
    req_init_put_req_d_next = req_init_put_req;
    req_init_core_req_d_next = !req_init_core_ready && req_init_core_req;
endfunction

// Synchronous register update
always_ff @(posedge req_init_clk or negedge req_init_nrst) 
begin : req_init_core_thread_ff
    if ( ~req_init_nrst ) begin
        req_init_put_req_d <= '0;
        req_init_core_req_d <= '0;
    end
    else begin
        req_init_put_req_d <= req_init_put_req_d_next;
        req_init_core_req_d <= req_init_core_req_d_next;
    end
end

//------------------------------------------------------------------------------
// Method process: req_init_req_control (sct_initiator.h:253:5) 

always_comb 
begin : req_init_req_control     // sct_initiator.h:253:5
    logic A;
    A = req_init_put_req != req_init_put_req_d;
    if (A)
    begin
        req_init_core_req = 1'd1;
    end else begin
        req_init_core_req = req_init_core_req_d;
    end
end

//------------------------------------------------------------------------------
// Method process: resp_target_ready_control (sct_target.h:238:5) 

always_comb 
begin : resp_target_ready_control     // sct_target.h:238:5
    logic A;
    A = resp_target_get_req != resp_target_get_req_d;
    if (A)
    begin
        resp_target_core_ready = 1'd1;
    end else begin
        resp_target_core_ready = !resp_target_core_req_d;
    end
end

//------------------------------------------------------------------------------
// Clocked THREAD: resp_target_core_thread (sct_target.h:247:5) 

// Thread-local variables
logic resp_target_get_req_d_next;
logic resp_target_core_req_d_next;
logic [31:0] resp_target_core_data_d_rdata_next;
logic resp_target_core_data_d_slverr_next;

// Next-state combinational logic
always_comb begin : resp_target_core_thread_comb     // sct_target.h:247:5
    resp_target_core_thread_func;
end
function void resp_target_core_thread_func;
    logic [31:0] TMP_0_rdata;
    logic TMP_0_slverr;
    resp_target_core_data_d_rdata_next = resp_target_core_data_d_rdata;
    resp_target_core_data_d_slverr_next = resp_target_core_data_d_slverr;
    resp_target_get_req_d_next = resp_target_get_req;
    resp_target_core_req_d_next = !resp_target_core_ready || resp_target_core_req;
    if (resp_target_core_req && resp_target_core_ready)
    begin
        resp_target_core_data_d_rdata_next = resp_target_core_data_rdata; resp_target_core_data_d_slverr_next = resp_target_core_data_slverr;
    end
endfunction

// Synchronous register update
always_ff @(posedge resp_target_clk or negedge resp_target_nrst) 
begin : resp_target_core_thread_ff
    if ( ~resp_target_nrst ) begin
        logic [31:0] TMP_0_rdata;
        logic TMP_0_slverr;
        resp_target_get_req_d <= '0;
        resp_target_core_req_d <= '0;
        TMP_0_rdata = '0;
        TMP_0_slverr = '0;
        resp_target_core_data_d_rdata <= TMP_0_rdata; resp_target_core_data_d_slverr <= TMP_0_slverr;
    end
    else begin
        resp_target_get_req_d <= resp_target_get_req_d_next;
        resp_target_core_req_d <= resp_target_core_req_d_next;
        resp_target_core_data_d_rdata <= resp_target_core_data_d_rdata_next;
        resp_target_core_data_d_slverr <= resp_target_core_data_d_slverr_next;
    end
end

//------------------------------------------------------------------------------
// Method process: resp_target_put_to_fifo (sct_target.h:224:5) 
// Empty process, no code generated 

//------------------------------------------------------------------------------
// Method process: resp_target_core_data_mux (sct_target.h:213:5) 

always_comb 
begin : resp_target_core_data_mux     // sct_target.h:213:5
    if (resp_target_core_ready)
    begin
        resp_target_core_data_out_rdata = resp_target_core_data_rdata; resp_target_core_data_out_slverr = resp_target_core_data_slverr;
    end else begin
        resp_target_core_data_out_rdata = resp_target_core_data_d_rdata; resp_target_core_data_out_slverr = resp_target_core_data_d_slverr;
    end
end

//------------------------------------------------------------------------------
// Clocked THREAD: apb_thread (apb_port.h:105:5) 

// Thread-local variables
logic req_init_put_req_next;
logic [7:0] req_init_core_data_addr_next;
logic req_init_core_data_write_next;
logic [31:0] req_init_core_data_wdata_next;
logic [3:0] req_init_core_data_wstrb_next;
logic resp_target_get_req_next;
logic PREADY_next;
logic [31:0] PRDATA_next;
logic PSLVERR_next;
logic [1:0] state;
logic [1:0] state_next;
logic [7:0] req_reg_addr;
logic [7:0] req_reg_addr_next;
logic req_reg_write;
logic req_reg_write_next;
logic [31:0] req_reg_wdata;
logic [31:0] req_reg_wdata_next;
logic [3:0] req_reg_wstrb;
logic [3:0] req_reg_wstrb_next;

// Next-state combinational logic
always_comb begin : apb_thread_comb     // apb_port.h:105:5
    apb_thread_func;
end
function void apb_thread_func;
    logic [31:0] resp_rdata;
    logic resp_slverr;
    logic req_done;
    logic resp_done;
    logic [7:0] TMP_0_addr;
    logic TMP_0_write;
    logic [31:0] TMP_0_wdata;
    logic [3:0] TMP_0_wstrb;
    logic [7:0] TMP_1_addr;
    logic TMP_1_write;
    logic [31:0] TMP_1_wdata;
    logic [3:0] TMP_1_wstrb;
    logic [31:0] TMP_2_rdata;
    logic TMP_2_slverr;
    logic TMP_3;
    logic TMP_4;
    logic enable;
    logic A;
    PRDATA_next = PRDATA;
    PSLVERR_next = PSLVERR;
    req_init_core_data_addr_next = req_init_core_data_addr;
    req_init_core_data_wdata_next = req_init_core_data_wdata;
    req_init_core_data_write_next = req_init_core_data_write;
    req_init_core_data_wstrb_next = req_init_core_data_wstrb;
    req_init_put_req_next = req_init_put_req;
    req_reg_addr_next = req_reg_addr;
    req_reg_wdata_next = req_reg_wdata;
    req_reg_write_next = req_reg_write;
    req_reg_wstrb_next = req_reg_wstrb;
    resp_target_get_req_next = resp_target_get_req;
    state_next = state;
    PREADY_next = '0;
    req_done = '0;
    resp_done = '0;
    case (state_next)
    0 : begin
        if (PSEL && !PENABLE)
        begin
            req_reg_addr_next = PADDR;
            req_reg_write_next = PWRITE;
            req_reg_wdata_next = PWDATA;
            req_reg_wstrb_next = PSTRB;
            state_next = STATE_REQUEST;
        end
    end
    1 : begin
        if (PSEL && PENABLE)
        begin
            // Call put() begin
            if (req_init_always_ready || req_init_core_ready)
            begin
                req_init_put_req_next = !req_init_put_req;
                req_init_core_data_addr_next = req_reg_addr_next; req_init_core_data_write_next = req_reg_write_next; req_init_core_data_wdata_next = req_reg_wdata_next; req_init_core_data_wstrb_next = req_reg_wstrb_next;
                TMP_3 = 1;
            end else begin
                TMP_3 = '0;
            end
            // Call put() end
            req_done = TMP_3;
            if (req_done)
            begin
                state_next = STATE_RESPONSE;
            end
        end else begin
            if (!PSEL)
            begin
                state_next = STATE_IDLE;
            end
        end
    end
    2 : begin
        enable = 1;
        // Call get() begin
        resp_rdata = resp_target_core_data_out_rdata; resp_slverr = resp_target_core_data_out_slverr;
        A = (!resp_target_core_ready || resp_target_core_req);
        if (A)
        begin
            resp_target_get_req_next = !resp_target_get_req;
            TMP_4 = enable;
        end else begin
            TMP_4 = '0;
        end
        // Call get() end
        resp_done = TMP_4;
        if (resp_done)
        begin
            PRDATA_next = resp_rdata;
            PSLVERR_next = resp_slverr;
            state_next = STATE_COMPLETE;
        end
    end
    3 : begin
        PREADY_next = PSEL && PENABLE;
        state_next = STATE_IDLE;
    end
    default : begin
        state_next = STATE_IDLE;
    end
    endcase
endfunction

// Synchronous register update
always_ff @(posedge PCLK or negedge PRESETn) 
begin : apb_thread_ff
    if ( ~PRESETn ) begin
        logic [31:0] resp_rdata;
        logic resp_slverr;
        logic [7:0] TMP_0_addr;
        logic TMP_0_write;
        logic [31:0] TMP_0_wdata;
        logic [3:0] TMP_0_wstrb;
        logic [7:0] TMP_1_addr;
        logic TMP_1_write;
        logic [31:0] TMP_1_wdata;
        logic [3:0] TMP_1_wstrb;
        logic [31:0] TMP_2_rdata;
        logic TMP_2_slverr;
        req_reg_addr <= '0;
        req_reg_write <= '0;
        req_reg_wdata <= '0;
        req_reg_wstrb <= '0;
        resp_rdata = '0;
        resp_slverr = '0;
        state <= '0;
        // Call reset_put() begin
        req_init_put_req <= '0;
        TMP_0_addr = '0;
        TMP_0_write = '0;
        TMP_0_wdata = '0;
        TMP_0_wstrb = '0;
        req_init_core_data_addr <= TMP_0_addr; req_init_core_data_write <= TMP_0_write; req_init_core_data_wdata <= TMP_0_wdata; req_init_core_data_wstrb <= TMP_0_wstrb;
        // Call reset_put() end
        // Call reset_get() begin
        resp_target_get_req <= '0;
        // Call reset_get() end
        TMP_1_addr = '0;
        TMP_1_write = '0;
        TMP_1_wdata = '0;
        TMP_1_wstrb = '0;
        req_reg_addr <= TMP_1_addr; req_reg_write <= TMP_1_write; req_reg_wdata <= TMP_1_wdata; req_reg_wstrb <= TMP_1_wstrb;
        TMP_2_rdata = '0;
        TMP_2_slverr = '0;
        resp_rdata = TMP_2_rdata; resp_slverr = TMP_2_slverr;
        state <= STATE_IDLE;
        PREADY <= '0;
        PRDATA <= '0;
        PSLVERR <= '0;
    end
    else begin
        req_init_put_req <= req_init_put_req_next;
        req_init_core_data_addr <= req_init_core_data_addr_next;
        req_init_core_data_write <= req_init_core_data_write_next;
        req_init_core_data_wdata <= req_init_core_data_wdata_next;
        req_init_core_data_wstrb <= req_init_core_data_wstrb_next;
        resp_target_get_req <= resp_target_get_req_next;
        PREADY <= PREADY_next;
        PRDATA <= PRDATA_next;
        PSLVERR <= PSLVERR_next;
        state <= state_next;
        req_reg_addr <= req_reg_addr_next;
        req_reg_write <= req_reg_write_next;
        req_reg_wdata <= req_reg_wdata_next;
        req_reg_wstrb <= req_reg_wstrb_next;
    end
end

endmodule


