//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.4.17
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: A ()
//
module A // "a_mod"
(
    input logic clk
);

// Variables generated for SystemC signals

//------------------------------------------------------------------------------
// Method process: literFromString (test_string_liter.cpp:36:5) 

always_comb 
begin : literFromString     // test_string_liter.cpp:36:5
    logic [5:0] ux;
    logic signed [9:0] ix;
    logic [64:0] bu;
    logic signed [99:0] bi;
    ux = 'b110011;
    ux = 42;
    ux = 5'd10;
    ux = 0;
    ux = 0;
    ux = 0;
    ix = -5'sd11;
    ix = -7'sh26;
    ix = 0;
    ix = -2'so1;
    ix = -2'sb1;
    bu = 0;
    bu = 65'h1FFFF1111FFFF1111;
    bu = 65'h1FFFF1111FFFF1111;
    bi = -6'sh1F;
    bi = -70'shAFFFF1111FFFF1111;
end

//------------------------------------------------------------------------------
// Method process: stringVarToInt (test_string_liter.cpp:73:5) 

always_comb 
begin : stringVarToInt     // test_string_liter.cpp:73:5
    logic [11:0] ux;
    logic signed [15:0] ix;
    logic [64:0] bu;
    logic signed [99:0] bi;
    ux = 42;
    ux = 42;
    ix = 43;
    ix = -7'sd42;
    bu = 65'h1FFFF1111FFFF1111;
    bu = 65'h1FFFF1111FFFF1111;
    bi = -70'shAFFFF1111FFFF1111;
    bi = -70'shAFFFF1111FFFF1111;
end

endmodule


