//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.6.28
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: test ()
//
module test // "t"
(
);

// Variables generated for SystemC signals
logic [31:0] s;
logic signed [31:0] t3;
logic signed [31:0] t3a;
logic signed [31:0] sa[3];
logic signed [31:0] sb[3];
logic signed [31:0] t5;

// Local parameters generated for C++ constants
localparam logic [2:0] c[3] = '{ 1, 2, 3 };
localparam logic signed [31:0] a[3] = '{ 2, 3, 4 };
localparam logic signed [31:0] b[3] = '{ 5, 6, 7 };
localparam logic signed [11:0] bx[3] = '{ 8, -5'sd9, 10 };
localparam logic signed [31:0] r[3] = '{ 1, 2, 3 };
localparam logic signed [31:0] p[3] = '{ 1, 2, 3 };
localparam logic signed [31:0] q[3] = '{ 1, 2, 3 };
localparam logic signed [31:0] g[3] = '{ 1, -3'sd2, 3 };
localparam logic [63:0] g1[3] = '{ 4, 5, 6 };
localparam logic signed [31:0] h[3] = '{ 1, 2, 3 };

//------------------------------------------------------------------------------
// Method process: const_array_test (test_std_array.cpp:49:5) 

always_comb 
begin : const_array_test     // test_std_array.cpp:49:5
    integer l;
    integer unsigned i;
    i = s;
    l = a[1];
    l = b[2];
    l = c[0];
    l = 32'(32'(32'(a[i] + a[i + 1]) + a[s]) + a[c[i]]);
    l = 32'(32'(32'(b[i] + b[i + 1]) + b[s]) + b[c[i]]);
    l = bx[0];
    l = 2'sd1 - bx[i - 1];
end

//------------------------------------------------------------------------------
// Method process: array_test (test_std_array.cpp:72:5) 

// Process-local variables
logic signed [31:0] f[3];
logic signed [31:0] d[3];
logic signed [31:0] e[3][2];

always_comb 
begin : array_test     // test_std_array.cpp:72:5
    integer l;
    integer unsigned i;
    i = s;
    f[0] = 41;
    d[0] = 42;
    d[1] = c[i];
    l = f[0];
    l = d[0];
    l = |d[1] ? d[f[1]] : e[s + 1][1];
    if (|e[2][l])
    begin
        e[0][1] = d[i];
    end
end

//------------------------------------------------------------------------------
// Method process: static_const_array_test (test_std_array.cpp:111:5) 

always_comb 
begin : static_const_array_test     // test_std_array.cpp:111:5
    integer l;
    integer unsigned i;
    i = s;
    l = 32'(32'(r[0] + p[0]) + q[0]);
    l = 64'(g[0] + g1[1]);
    l = h[0];
    l = 32'(r[0] + q[1]);
    l = r[i] / q[i - 1];
    l = 64'(g[r[1]] + g1[q[i]]);
end

//------------------------------------------------------------------------------
// Method process: local_array_test (test_std_array.cpp:128:5) 

always_comb 
begin : local_array_test     // test_std_array.cpp:128:5
    integer n[3];
    integer m[3];
    logic [15:0] k[3];
    integer p_1[3];
    integer mm[3][2];
    integer pp[3][2];
    n[0] = 1; n[1] = 2; n[2] = 3;
    k[0] = 0; k[1] = 0; k[2] = 0;
    p_1[0] = 2; p_1[1] = 3; p_1[2] = 4;
    m[0] = 41;
    k[s + 1] = m[s];
    m[s] = 32'(7'sd42 + p_1[1]);
    t3 = 32'(m[0] + n[s]) + k[1] + p_1[s - 1];
    pp[0][0] = 1; pp[0][1] = 2; pp[1][0] = 3; pp[1][1] = 4; pp[2][0] = 5; pp[2][1] = 6;
    mm[0][1] = s;
    pp[2][0] = s;
    t3 = mm[0][s];
    t3 = 32'(mm[s - 1][1] + pp[s][0]);
end

//------------------------------------------------------------------------------
// Method process: local_array_oper_test (test_std_array.cpp:151:5) 

always_comb 
begin : local_array_oper_test     // test_std_array.cpp:151:5
    integer m[2];
    integer k[2];
    integer mm[3][2];
    integer kk[3][2];
    logic lb;
    m = k;
    mm = kk;
    mm[0] = m;
    t3a = 32'(m[0] + mm[0][0]);
    lb = m[0] == k[1];
    t3a = lb ? m[0] : mm[0][0];
end

//------------------------------------------------------------------------------
// Method process: local_array_sig_test (test_std_array.cpp:179:5) 

always_comb 
begin : local_array_sig_test     // test_std_array.cpp:179:5
    sb[s] = 32'(sa[1] + 2'sd1);
    t5 = sa[0];
end

endmodule


