//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.5.15
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: top ()
//
module top // "tb_inst.top_inst"
(
    input logic clk,
    input logic rst
);

// Variables generated for SystemC signals
logic minst_s[2];
logic signed [31:0] minst_t1[2];

//------------------------------------------------------------------------------
// Method process: minst_metProc (test_mif_array_with_chan.cpp:26:5) 

always_comb 
begin : minst_metProc     // test_mif_array_with_chan.cpp:26:5
    logic d;
    d = minst_s[0];
    minst_t1[0] = d;
end

//------------------------------------------------------------------------------
// Method process: minst_metProc0 (test_mif_array_with_chan.cpp:26:5) 

always_comb 
begin : minst_metProc0     // test_mif_array_with_chan.cpp:26:5
    logic d;
    d = minst_s[1];
    minst_t1[1] = d;
end

endmodule


