//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.4.16
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: A ()
//
module A // "top"
(
    input logic clk
);

// Variables generated for SystemC signals

// Local parameters generated for C++ constants
localparam logic ma[3] = '{ 0, 0, 0 };
localparam logic signed [31:0] mb[3] = '{ 0, 0, 0 };
localparam logic [3:0] mc[3] = '{ 0, 0, 0 };
localparam logic signed [3:0] md[3] = '{ 0, 0, 0 };
localparam logic mma[3] = '{ 1, 0, 0 };
localparam logic signed [31:0] mmb[3] = '{ 1, 2, 0 };
localparam logic [3:0] mmc[3] = '{ 3, 0, 0 };
localparam logic signed [3:0] mmd[3] = '{ 4, -4'sd5, 0 };

//------------------------------------------------------------------------------
// Method process: init_3D_array_local (test_array_init.cpp:34:5) 

always_comb 
begin : init_3D_array_local     // test_array_init.cpp:34:5
    logic [3:0] a[2][3][2];
    integer b[2][3][2];
    logic c[2][3][2];
    logic signed [63:0] d[2][3][2];
    a[0][0][0] = 0; a[0][0][1] = 0; a[0][1][0] = 0; a[0][1][1] = 0; a[0][2][0] = 0; a[0][2][1] = 0; a[1][0][0] = 0; a[1][0][1] = 0; a[1][1][0] = 0; a[1][1][1] = 0; a[1][2][0] = 0; a[1][2][1] = 0;
    b[0][0][0] = 0; b[0][0][1] = 0; b[0][1][0] = 0; b[0][1][1] = 0; b[0][2][0] = 0; b[0][2][1] = 0; b[1][0][0] = 0; b[1][0][1] = 0; b[1][1][0] = 0; b[1][1][1] = 0; b[1][2][0] = 0; b[1][2][1] = 0;
    c[0][0][0] = 1; c[0][0][1] = 0; c[0][1][0] = 1; c[0][1][1] = 0; c[0][2][0] = 1; c[0][2][1] = 1; c[1][0][0] = 0; c[1][0][1] = 0; c[1][1][0] = 0; c[1][1][1] = 0; c[1][2][0] = 0; c[1][2][1] = 0;
    d[0][0][0] = 1; d[0][0][1] = 2; d[0][1][0] = -3'sd3; d[0][1][1] = 4; d[0][2][0] = 5; d[0][2][1] = 6; d[1][0][0] = 0; d[1][0][1] = 0; d[1][1][0] = 0; d[1][1][1] = 0; d[1][2][0] = 0; d[1][2][1] = 0;
end

//------------------------------------------------------------------------------
// Method process: no_init_2D_array_local (test_array_init.cpp:63:5) 

always_comb 
begin : no_init_2D_array_local     // test_array_init.cpp:63:5
    logic [3:0] a[3][2];
    logic signed [3:0] b[3][2];
    logic c[3][2];
    integer d[3][2];
    a[0][0] = 0; a[0][1] = 0; a[1][0] = 0; a[1][1] = 0; a[2][0] = 0; a[2][1] = 0;
    b[0][0] = 0; b[0][1] = 0; b[1][0] = 0; b[1][1] = 0; b[2][0] = 0; b[2][1] = 0;
    c[0][0] = 0; c[0][1] = 0; c[1][0] = 0; c[1][1] = 0; c[2][0] = 0; c[2][1] = 0;
    d[0][0] = 0; d[0][1] = 0; d[1][0] = 0; d[1][1] = 0; d[2][0] = 0; d[2][1] = 0;
end

//------------------------------------------------------------------------------
// Method process: part_init_2D_array_local (test_array_init.cpp:98:5) 

always_comb 
begin : part_init_2D_array_local     // test_array_init.cpp:98:5
    logic [3:0] b[3][2];
    logic c[3][2];
    integer d[3][2];
    b[0][0] = 1; b[0][1] = 2; b[1][0] = 3; b[1][1] = 4; b[2][0] = 0; b[2][1] = 0;
    c[0][0] = 1; c[0][1] = 0; c[1][0] = 0; c[1][1] = 0; c[2][0] = 0; c[2][1] = 0;
    d[0][0] = 1; d[0][1] = 2; d[1][0] = -3'sd3; d[1][1] = 4; d[2][0] = 0; d[2][1] = 0;
end

//------------------------------------------------------------------------------
// Method process: full_init_2D_array_local (test_array_init.cpp:129:6) 

always_comb 
begin : full_init_2D_array_local     // test_array_init.cpp:129:6
    logic signed [3:0] a[3][2];
    logic [3:0] b[2][3];
    logic c[3][2];
    integer d[3][2];
    a[0][0] = 1; a[0][1] = 2; a[1][0] = 3; a[1][1] = 4; a[2][0] = -4'sd5; a[2][1] = 6;
    b[0][0] = 1; b[0][1] = 2; b[0][2] = 3; b[1][0] = 4; b[1][1] = 5; b[1][2] = 6;
    c[0][0] = 1; c[0][1] = 0; c[1][0] = 1; c[1][1] = 0; c[2][0] = 0; c[2][1] = 1;
    d[0][0] = 1; d[0][1] = 2; d[1][0] = 3; d[1][1] = 4; d[2][0] = -4'sd5; d[2][1] = 6;
end

//------------------------------------------------------------------------------
// Method process: sc_no_init (test_array_init.cpp:164:5) 

always_comb 
begin : sc_no_init     // test_array_init.cpp:164:5
    logic [3:0] c[3];
    c[0] = 0; c[1] = 0; c[2] = 0;
end

//------------------------------------------------------------------------------
// Method process: no_init_local1 (test_array_init.cpp:171:5) 

always_comb 
begin : no_init_local1     // test_array_init.cpp:171:5
    logic a[3];
    integer b[3];
    logic [3:0] c[3];
    logic signed [3:0] d[3];
    a[0] = 0; a[1] = 0; a[2] = 0;
    b[0] = 0; b[1] = 0; b[2] = 0;
    c[0] = 0; c[1] = 0; c[2] = 0;
    d[0] = 0; d[1] = 0; d[2] = 0;
end

//------------------------------------------------------------------------------
// Method process: part_init_local1 (test_array_init.cpp:196:5) 

always_comb 
begin : part_init_local1     // test_array_init.cpp:196:5
    logic a[3];
    integer b[3];
    logic [3:0] c[3];
    logic signed [3:0] d[3];
    a[0] = 1; a[1] = 0; a[2] = 0;
    b[0] = 1; b[1] = 2; b[2] = 0;
    c[0] = 3; c[1] = 0; c[2] = 0;
    d[0] = 4; d[1] = -4'sd5; d[2] = 0;
end

//------------------------------------------------------------------------------
// Method process: no_init_member1 (test_array_init.cpp:223:5) 

always_comb 
begin : no_init_member1     // test_array_init.cpp:223:5
end

//------------------------------------------------------------------------------
// Method process: part_init_member1 (test_array_init.cpp:246:5) 

always_comb 
begin : part_init_member1     // test_array_init.cpp:246:5
end

endmodule


