//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.4.16
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: B_top ()
//
module B_top // "b_mod"
(
);


//------------------------------------------------------------------------------
// Child module instances

A a_mod
(

);

endmodule



//==============================================================================
//
// Module: A (test_stdouts_prints.cpp:117:5)
//
module A // "b_mod.a_mod"
(
);

// Variables generated for SystemC signals
logic dummy;

// Local parameters generated for C++ constants
localparam logic signed [31:0] m = 11;

//------------------------------------------------------------------------------
// Method process: meth_print (test_stdouts_prints.cpp:48:5) 

always_comb 
begin : meth_print     // test_stdouts_prints.cpp:48:5
    integer i;
    i = m;
end

//------------------------------------------------------------------------------
// Method process: meth_printf (test_stdouts_prints.cpp:55:5) 

always_comb 
begin : meth_printf     // test_stdouts_prints.cpp:55:5
end

//------------------------------------------------------------------------------
// Method process: meth_cerr (test_stdouts_prints.cpp:63:5) 

always_comb 
begin : meth_cerr     // test_stdouts_prints.cpp:63:5
    logic a;
    a = dummy;
end

//------------------------------------------------------------------------------
// Method process: meth_cout (test_stdouts_prints.cpp:77:5) 

always_comb 
begin : meth_cout     // test_stdouts_prints.cpp:77:5
    integer i;
    integer unsigned computeEn;
    computeEn = 1;
end

//------------------------------------------------------------------------------
// Method process: meth_cin (test_stdouts_prints.cpp:93:5) 

always_comb 
begin : meth_cin     // test_stdouts_prints.cpp:93:5
    integer i;
end

//------------------------------------------------------------------------------
// Method process: meth_sc_print (test_stdouts_prints.cpp:98:5) 

always_comb 
begin : meth_sc_print     // test_stdouts_prints.cpp:98:5
end

//------------------------------------------------------------------------------
// Method process: meth_sc_dump (test_stdouts_prints.cpp:103:5) 

always_comb 
begin : meth_sc_dump     // test_stdouts_prints.cpp:103:5
end

//------------------------------------------------------------------------------
// Method process: meth_sc_kind (test_stdouts_prints.cpp:108:5) 

always_comb 
begin : meth_sc_kind     // test_stdouts_prints.cpp:108:5
end

endmodule


