//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.5.11
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: simple_test ()
//
module simple_test // "test_top.dut"
(
    input logic clk,
    input logic nrst
);

// Variables generated for SystemC signals
logic run_ready;
logic run_req;
logic [15:0] run_data;
logic resp_ready;
logic resp_req;
logic [15:0] resp_data;

// Local parameters generated for C++ constants
localparam logic [31:0] N = 4;

//------------------------------------------------------------------------------
// Clocked THREAD: init_thread (fifo_single.h:111:5) 

// Thread-local variables
logic run_req_next;
logic [15:0] run_data_next;
logic signed [31:0] i;
logic signed [31:0] i_next;
logic signed [31:0] i0;
logic signed [31:0] i_next0;
logic [2:0] init_thread_PROC_STATE;
logic [2:0] init_thread_PROC_STATE_next;

// Next-state combinational logic
always_comb begin : init_thread_comb     // fifo_single.h:111:5
    init_thread_func;
end
function void init_thread_func;
    logic [15:0] data;
    i_next = i;
    i_next0 = i0;
    run_data_next = run_data;
    run_req_next = run_req;
    init_thread_PROC_STATE_next = init_thread_PROC_STATE;
    
    case (init_thread_PROC_STATE)
        0: begin
            i_next = 0;
            if (!run_ready)
            begin
                init_thread_PROC_STATE_next = 1; return;    // fifo_single.h:119:32;
            end
            run_req_next = 1;
            run_data_next = 32 + i_next;
            init_thread_PROC_STATE_next = 2; return;    // fifo_single.h:121:13;
        end
        1: begin
            if (!run_ready)
            begin
                init_thread_PROC_STATE_next = 1; return;    // fifo_single.h:119:32;
            end
            run_req_next = 1;
            run_data_next = 32 + i_next;
            init_thread_PROC_STATE_next = 2; return;    // fifo_single.h:121:13;
        end
        2: begin
            ++i_next;
            if (i_next < N)
            begin
                if (!run_ready)
                begin
                    init_thread_PROC_STATE_next = 1; return;    // fifo_single.h:119:32;
                end
                run_req_next = 1;
                run_data_next = 32 + i_next;
                init_thread_PROC_STATE_next = 2; return;    // fifo_single.h:121:13;
            end
            data = 0;
            i_next0 = 0;
            if (!resp_req)
            begin
                init_thread_PROC_STATE_next = 3; return;    // fifo_single.h:127:31;
            end
            init_thread_PROC_STATE_next = 4; return;    // fifo_single.h:129:13;
        end
        3: begin
            if (!resp_req)
            begin
                init_thread_PROC_STATE_next = 3; return;    // fifo_single.h:127:31;
            end
            init_thread_PROC_STATE_next = 4; return;    // fifo_single.h:129:13;
        end
        4: begin
            ++i_next0;
            if (i_next0 < N)
            begin
                if (!resp_req)
                begin
                    init_thread_PROC_STATE_next = 3; return;    // fifo_single.h:127:31;
                end
                init_thread_PROC_STATE_next = 4; return;    // fifo_single.h:129:13;
            end
            init_thread_PROC_STATE_next = 5; return;    // fifo_single.h:132:9;
        end
        5: begin
            init_thread_PROC_STATE_next = 6; return;    // fifo_single.h:136:13;
        end
        6: begin
            init_thread_PROC_STATE_next = 6; return;    // fifo_single.h:136:13;
        end
    endcase
endfunction

// Synchronous register update
always_ff @(posedge clk or negedge nrst) 
begin : init_thread_ff
    if ( ~nrst ) begin
        run_req <= 0;
        run_data <= 0;
        resp_ready <= 1;
        init_thread_PROC_STATE <= 0;    // fifo_single.h:116:9;
    end
    else begin
        run_req <= run_req_next;
        run_data <= run_data_next;
        i <= i_next;
        i0 <= i_next0;
        init_thread_PROC_STATE <= init_thread_PROC_STATE_next;
    end
end


//------------------------------------------------------------------------------
// Child module instances

A a
(
  .clk(clk),
  .nrst(nrst),
  .run_ready(run_ready),
  .run_req(run_req),
  .run_data(run_data),
  .resp_ready(resp_ready),
  .resp_req(resp_req),
  .resp_data(resp_data)
);

endmodule



//==============================================================================
//
// Module: A (fifo_single.h:89:5)
//
module A // "test_top.dut.a"
(
    input logic clk,
    input logic nrst,
    output logic run_ready,
    input logic run_req,
    input logic [15:0] run_data,
    input logic resp_ready,
    output logic resp_req,
    output logic [15:0] resp_data
);

// Variables generated for SystemC signals
logic [15:0] fifo_buffer[2];
logic fifo_put_req;
logic fifo_put_req_d;
logic fifo_get_req;
logic fifo_get_req_d;
logic [15:0] fifo_data_in;
logic [15:0] fifo_data_out;
logic fifo_ready_push;
logic fifo_out_valid;
logic fifo_pop_indx;
logic fifo_push_indx;
logic [1:0] fifo_element_num;
logic [1:0] fifo_element_num_d;
logic fifo_not_empty_d;
logic fifo_clk;
logic fifo_nrst;

// Local parameters generated for C++ constants
localparam logic fifo_SYNC_VALID = 1;
localparam logic fifo_SYNC_READY = 1;
localparam logic fifo_INIT_BUFFER = 0;
localparam logic fifo_cthread_put = 1;
localparam logic fifo_cthread_get = 1;

// Assignments generated for C++ channel arrays
assign fifo_clk = clk;
assign fifo_nrst = nrst;

//------------------------------------------------------------------------------
// Method process: fifo_asyncProc (sct_fifo.h:267:5) 

always_comb 
begin : fifo_asyncProc     // sct_fifo.h:267:5
    logic outValid;
    logic readyPush;
    logic popIndx;
    logic notEmpty;
    logic notOne;
    logic notFullOne;
    logic notFull;
    logic push;
    logic pop;
    popIndx = 0;
    notEmpty = fifo_element_num_d != 0;
    notOne = fifo_element_num_d != 1;
    notFullOne = fifo_element_num_d != 2 - 1;
    notFull = fifo_element_num_d != 2;
    push = fifo_put_req != fifo_put_req_d;
    pop = fifo_get_req != fifo_get_req_d;
    if (fifo_cthread_get && pop)
    begin
        outValid = notEmpty && notOne;
        popIndx = (fifo_pop_indx == 2 - 1) ? 0 : fifo_pop_indx + 1;
    end else begin
        outValid = notEmpty;
        popIndx = fifo_pop_indx;
    end
    fifo_not_empty_d = notEmpty;
    if (fifo_cthread_put && push)
    begin
        readyPush = notFull && notFullOne;
    end else begin
        readyPush = notFull;
    end
    fifo_out_valid = outValid;
    fifo_data_out = fifo_buffer[popIndx];
    fifo_ready_push = readyPush;
    fifo_element_num = fifo_element_num_d;
    if (pop && !push)
    begin
        fifo_element_num = fifo_element_num_d - 1;
    end else begin
        if (!pop && push)
        begin
            fifo_element_num = fifo_element_num_d + 1;
        end
    end
end

//------------------------------------------------------------------------------
// Clocked THREAD: fifo_syncProc (sct_fifo.h:320:5) 

// Thread-local variables
logic fifo_pop_indx_next;
logic fifo_push_indx_next;
logic fifo_put_req_d_next;
logic fifo_get_req_d_next;
logic [1:0] fifo_element_num_d_next;
logic [15:0] fifo_buffer_next[2];

// Next-state combinational logic
always_comb begin : fifo_syncProc_comb     // sct_fifo.h:320:5
    fifo_syncProc_func;
end
function void fifo_syncProc_func;
    logic push;
    logic pop;
    logic A;
    fifo_buffer_next = fifo_buffer;
    fifo_element_num_d_next = fifo_element_num_d;
    fifo_get_req_d_next = fifo_get_req_d;
    fifo_pop_indx_next = fifo_pop_indx;
    fifo_push_indx_next = fifo_push_indx;
    fifo_put_req_d_next = fifo_put_req_d;
    push = fifo_put_req != fifo_put_req_d;
    pop = fifo_get_req != fifo_get_req_d;
    if (pop && fifo_not_empty_d)
    begin
        fifo_pop_indx_next = (fifo_pop_indx == 2 - 1) ? 0 : fifo_pop_indx + 1;
    end
    A = 0;
    if (push && !A)
    begin
        fifo_buffer_next[fifo_push_indx] = fifo_data_in;
        fifo_push_indx_next = (fifo_push_indx == 2 - 1) ? 0 : fifo_push_indx + 1;
    end
    fifo_put_req_d_next = fifo_put_req;
    fifo_get_req_d_next = fifo_get_req;
    fifo_element_num_d_next = fifo_element_num;
endfunction

// Synchronous register update
always_ff @(posedge fifo_clk or negedge fifo_nrst) 
begin : fifo_syncProc_ff
    if ( ~fifo_nrst ) begin
        fifo_pop_indx <= 0;
        fifo_push_indx <= 0;
        fifo_put_req_d <= 0;
        fifo_get_req_d <= 0;
        fifo_element_num_d <= 0;
        fifo_buffer[0] <= 0;
    end
    else begin
        fifo_pop_indx <= fifo_pop_indx_next;
        fifo_push_indx <= fifo_push_indx_next;
        fifo_put_req_d <= fifo_put_req_d_next;
        fifo_get_req_d <= fifo_get_req_d_next;
        fifo_element_num_d <= fifo_element_num_d_next;
        fifo_buffer <= fifo_buffer_next;
    end
end

//------------------------------------------------------------------------------
// Clocked THREAD: threadProc (fifo_single.h:47:5) 

// Thread-local variables
logic run_ready_next;
logic resp_req_next;
logic [15:0] resp_data_next;
logic fifo_get_req_next;
logic fifo_put_req_next;
logic [15:0] fifo_data_in_next;

// Next-state combinational logic
always_comb begin : threadProc_comb     // fifo_single.h:47:5
    threadProc_func;
end
function void threadProc_func;
    logic TMP_0;
    logic TMP_1;
    logic [15:0] data;
    logic TMP_2;
    logic TMP_3;
    logic [15:0] TMP_4;
    logic [15:0] data_1;
    fifo_data_in_next = fifo_data_in;
    fifo_get_req_next = fifo_get_req;
    fifo_put_req_next = fifo_put_req;
    resp_data_next = resp_data;
    resp_req_next = resp_req;
    run_ready_next = run_ready;
    // Call ready() begin
    TMP_0 = fifo_ready_push;
    // Call ready() end
    run_ready_next = TMP_0;
    // Call ready() begin
    TMP_1 = fifo_ready_push;
    // Call ready() end
    if (run_req && TMP_1)
    begin
        data = run_data;
        // Call put() begin
        fifo_data_in_next = data;
        if (fifo_ready_push)
        begin
            fifo_put_req_next = !fifo_put_req;
            TMP_2 = 1;
        end else begin
            TMP_2 = 0;
        end
        // Call put() end
    end else begin
        // Call request() begin
        TMP_3 = fifo_out_valid;
        // Call request() end
        if (TMP_3 && resp_ready)
        begin
            // Call get() begin
            if (fifo_out_valid)
            begin
                fifo_get_req_next = !fifo_get_req;
            end
            TMP_4 = fifo_data_out;
            // Call get() end
            data_1 = TMP_4;
            resp_req_next = 1;
            resp_data_next = data_1;
        end
    end
endfunction

// Synchronous register update
always_ff @(posedge clk or negedge nrst) 
begin : threadProc_ff
    if ( ~nrst ) begin
        run_ready <= 0;
        resp_req <= 0;
        resp_data <= 0;
        // Call reset() begin
        // Call reset_get() begin
        fifo_get_req <= 0;
        // Call reset_get() end
        // Call reset_put() begin
        fifo_put_req <= 0;
        fifo_data_in <= 0;
        // Call reset_put() end
        // Call reset() end
    end
    else begin
        run_ready <= run_ready_next;
        resp_req <= resp_req_next;
        resp_data <= resp_data_next;
        fifo_get_req <= fifo_get_req_next;
        fifo_put_req <= fifo_put_req_next;
        fifo_data_in <= fifo_data_in_next;
    end
end

endmodule


