//==============================================================================
//
// The code is generated by Intel Compiler for SystemC, version 1.3.14
// see more information at https://github.com/intel/systemc-compiler
//
//==============================================================================

//==============================================================================
//
// Module: Top ()
//
module Top // "top"
(
    input logic clk
);

// SystemC signals
logic signed [31:0] minst_t;
logic signed [31:0] t;

// C++ data variables
localparam logic [31:0] minst_B = 'd43;
localparam logic [31:0] minst_A = 'd42;
localparam logic [31:0] minst_AA = 'd42;
localparam logic [31:0] minst_C = 'd44;
localparam logic [31:0] minst_D = 'd45;
localparam logic [31:0] minst_N = 'd44;
localparam logic [31:0] minst_M = 'd45;

//------------------------------------------------------------------------------
// Method process: minst_mifProc (test_mif_const.cpp:33:5) 

always_comb 
begin : minst_mifProc     // test_mif_const.cpp:33:5
    integer unsigned i;
    i = minst_N;
    if (1)
    begin
        minst_t = i;
    end
end

//------------------------------------------------------------------------------
// Method process: topProc (test_mif_const.cpp:58:5) 

always_comb 
begin : topProc     // test_mif_const.cpp:58:5
    integer unsigned i;
    i = minst_A;
    i = minst_AA;
    i = AAA;
    if (1)
    begin
        t = i + minst_D;
    end
end

endmodule


